import { useState } from "react";
import Navbar from "@/components/Navbar";
import ResultCard from "@/components/ResultCard";
import { analyzeSequence, hashSequence } from "@/lib/api";

export default function AnalyzePage() {
  const [filename, setFilename] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [hash, setHash] = useState("");
  const [status, setStatus] = useState("");
  const [isWorking, setIsWorking] = useState(false);

  const handleAnalyze = async () => {
    if (!filename) {
      setStatus("Provide a filename to analyze.");
      return;
    }
    setIsWorking(true);
    setStatus("");
    try {
      const result = await analyzeSequence(filename);
      setAnalysis(result);
      setStatus("Analysis completed.");
    } catch (error) {
      setStatus(error.message);
    } finally {
      setIsWorking(false);
    }
  };

  const handleHash = async () => {
    if (!filename) {
      setStatus("Provide a filename before hashing.");
      return;
    }
    setIsWorking(true);
    try {
      const resp = await hashSequence(filename);
      setHash(resp.hash);
      setStatus("Hash generated.");
    } catch (error) {
      setStatus(error.message);
    } finally {
      setIsWorking(false);
    }
  };

  return (
    <div>
      <Navbar />
      <main className="mx-auto max-w-5xl px-6 py-12 space-y-8">
        <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
          <p className="text-xs uppercase tracking-[0.4em] text-slate-500">Module 02</p>
          <h1 className="mt-2 text-3xl font-bold">Sequence Analysis</h1>
          <p className="mt-2 text-slate-400">
            Provide the filename of a previously uploaded or fetched FASTA file to run Biopython QC.
            Hashes & ledger entries are created automatically during ingestion—you can still rehash for verification.
          </p>
          <div className="mt-6 flex flex-col gap-4 md:flex-row">
            <input
              value={filename}
              onChange={(e) => setFilename(e.target.value)}
              placeholder="example.fasta"
              className="flex-1 rounded border border-slate-700 bg-slate-950/60 px-4 py-3 text-sm"
            />
            <button
              type="button"
              onClick={handleAnalyze}
              disabled={isWorking}
              className="rounded bg-neon px-6 py-3 font-semibold text-slate-950 disabled:opacity-60"
            >
              Analyze
            </button>
          </div>
          <div className="mt-4 flex flex-col gap-3 md:flex-row">
            <button
              type="button"
              onClick={handleHash}
              disabled={isWorking}
              className="rounded border border-slate-700 px-4 py-2 text-sm hover:border-slate-500 disabled:opacity-60"
            >
              Generate Hash
            </button>
            {hash && (
              <span className="break-all font-mono text-xs text-slate-400">
                Hash: {hash}
              </span>
            )}
          </div>
          {status && <p className="mt-3 text-sm text-slate-300">{status}</p>}
          <p className="mt-3 text-xs text-slate-500">
            Tip: Visit the Ledger Observatory to see new blocks generated by uploads and remote fetches.
          </p>
        </section>

        <ResultCard data={analysis} />
      </main>
    </div>
  );
}

