import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import ResultCard from "@/components/ResultCard";
import { analyzeSequence, hashSequence, getAnalysisHistoryByFilename } from "@/lib/api";

export default function AnalyzePage() {
  const router = useRouter();
  const [filename, setFilename] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [hash, setHash] = useState("");
  const [status, setStatus] = useState("");
  const [isWorking, setIsWorking] = useState(false);
  const [history, setHistory] = useState([]);

  const handleAnalyze = async () => {
    if (!filename) {
      setStatus("Provide a filename to analyze.");
      return;
    }
    setIsWorking(true);
    setStatus("");
    try {
      const result = await analyzeSequence(filename);
      setAnalysis(result);
      setStatus("Analysis completed.");
    } catch (error) {
      setStatus(error.message);
    } finally {
      setIsWorking(false);
    }
  };

  const handleHash = async () => {
    if (!filename) {
      setStatus("Provide a filename before hashing.");
      return;
    }
    setIsWorking(true);
    try {
      const resp = await hashSequence(filename);
      setHash(resp.hash);
      setStatus("Hash generated.");
    } catch (error) {
      setStatus(error.message);
    } finally {
      setIsWorking(false);
    }
  };

  // Load filename from query params
  useEffect(() => {
    if (router.query.filename) {
      setFilename(router.query.filename);
    }
  }, [router.query]);

  // Load history when filename changes
  useEffect(() => {
    if (filename) {
      getAnalysisHistoryByFilename(filename, 5)
        .then((resp) => {
          setHistory(resp.history || []);
          // Auto-load most recent analysis if available
          if (resp.history?.length > 0 && !analysis) {
            const latest = resp.history[0];
            setAnalysis({
              filename: latest.filename,
              length: latest.analysis?.length || 0,
              gc_percent: latest.analysis?.gc_percent || 0,
              sequence_preview: latest.analysis?.sequence_preview || "",
            });
          }
        })
        .catch(() => {
          // Ignore errors
        });
    }
  }, [filename]);

  return (
    <div>
      <Navbar />
      <main className="mx-auto max-w-5xl px-6 py-12 space-y-8">
        <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
          <p className="text-xs uppercase tracking-[0.4em] text-slate-500">Module 02</p>
          <h1 className="mt-2 text-3xl font-bold">Sequence Analysis</h1>
          <p className="mt-2 text-slate-400">
            Provide the filename of a previously uploaded or fetched FASTA file to run Biopython QC.
            Hashes & ledger entries are created automatically during ingestion—you can still rehash for verification.
          </p>
          <div className="mt-6 flex flex-col gap-4 md:flex-row">
            <input
              value={filename}
              onChange={(e) => setFilename(e.target.value)}
              placeholder="example.fasta"
              className="flex-1 rounded border border-slate-700 bg-slate-950/60 px-4 py-3 text-sm"
            />
            <button
              type="button"
              onClick={handleAnalyze}
              disabled={isWorking}
              className="rounded bg-neon px-6 py-3 font-semibold text-slate-950 disabled:opacity-60"
            >
              Analyze
            </button>
          </div>
          <div className="mt-4 flex flex-col gap-3 md:flex-row">
            <button
              type="button"
              onClick={handleHash}
              disabled={isWorking}
              className="rounded border border-slate-700 px-4 py-2 text-sm hover:border-slate-500 disabled:opacity-60"
            >
              Generate Hash
            </button>
            {hash && (
              <span className="break-all font-mono text-xs text-slate-400">
                Hash: {hash}
              </span>
            )}
          </div>
          {status && <p className="mt-3 text-sm text-slate-300">{status}</p>}
          <p className="mt-3 text-xs text-slate-500">
            Tip: Visit the Ledger Observatory to see new blocks generated by uploads and remote fetches.
          </p>
        </section>

        {/* Recent History */}
        {history.length > 0 && (
          <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <p className="text-xs uppercase tracking-[0.4em] text-slate-500">
                  Recent History
                </p>
                <h2 className="mt-1 text-xl font-semibold">
                  Past Analyses for {filename}
                </h2>
              </div>
              <Link
                href="/history"
                className="text-sm font-semibold text-neon hover:text-cyan-200"
              >
                View All →
              </Link>
            </div>
            <div className="space-y-2">
              {history.slice(0, 3).map((entry) => (
                <div
                  key={entry.id}
                  className="rounded-lg border border-slate-800 bg-slate-950/60 p-3"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4 text-sm">
                      <span className="text-bioGreen">
                        {entry.analysis?.length?.toLocaleString() || "N/A"} bp
                      </span>
                      <span className="text-neon">
                        GC: {entry.analysis?.gc_percent?.toFixed(2) || "N/A"}%
                      </span>
                      <span className="text-slate-400 text-xs">
                        {new Date(entry.timestamp).toLocaleString()}
                      </span>
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        setAnalysis({
                          filename: entry.filename,
                          length: entry.analysis?.length || 0,
                          gc_percent: entry.analysis?.gc_percent || 0,
                          sequence_preview: entry.analysis?.sequence_preview || "",
                        });
                      }}
                      className="rounded border border-slate-700 px-2 py-1 text-xs hover:border-neon"
                    >
                      Load
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        <ResultCard data={analysis} />
      </main>
    </div>
  );
}

